version: "3"
services:
  database:
    restart: always
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: symfony_chatApp
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql

  webserver:
    image: khaleddwm/chatapp:v1.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - etc_data:/etc

  mercure-hub:
    restart: always
    image: dunglas/mercure:v0.9
    ports:
      - 3000:80
    environment:
      JWT_KEY: benkod37
      ALLOW_ANONYMOUS: 1
      PUBLISH_ALLOWED_ORIGINS: '*'
      CORS_ALLOWED_ORIGINS: '*'
    expose:
      - 3000

volumes:
  db_data: {}
  etc_data: {}
